### ISSUE TITLE
No module named keys

### ISSUE THREAD

**Issue by hexnickk** [CTFd/DynamicValueChallenge#10]
Latest CTFd, latest DynamicValueChallenge. Isn't it maintained anymore?

```
ctfd_1   | Traceback (most recent call last):
ctfd_1   |   File "manage.py", line 8, in <module>
ctfd_1   |     app = create_app()
ctfd_1   |   File "/opt/CTFd/CTFd/__init__.py", line 210, in create_app
ctfd_1   |     init_plugins(app)
ctfd_1   |   File "/opt/CTFd/CTFd/plugins/__init__.py", line 183, in init_plugins
ctfd_1   |     module = importlib.import_module(module, package='CTFd.plugins')
ctfd_1   |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
ctfd_1   |     __import__(name)
ctfd_1   |   File "/opt/CTFd/CTFd/plugins/DynamicValueChallenge/__init__.py", line 4, in <module>
ctfd_1   |     from CTFd.plugins.keys import get_key_class
ctfd_1   | ImportError: No module named keys
```

there is no plugins/keys folder in CTFd
```
→ ls plugins
challenges  dynamic_challenges  DynamicValueChallenge  flags  __init__.py
```

**Comment by hexnickk** [comment]
oh, there is dynamic_challenges folder. My fault, sorry)
